version: '3'
services:
  app:
    restart: always
    build: .
    container_name: 'bigquery-tutorial'
    working_dir: '/usr/src'
    tty: true
    volumes:
      - ./src:/usr/src
    environment: 
      - GOOGLE_APPLICATION_CREDENTIALS=./bigquery-tutorial.json